# Generated by Django 3.1.3 on 2020-11-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcNumber', models.CharField(max_length=75, verbose_name='TC No')),
                ('name', models.CharField(max_length=75, verbose_name='Ad')),
                ('surname', models.CharField(max_length=75, verbose_name='Soyad')),
                ('school', models.CharField(max_length=75, verbose_name='Okul')),
                ('faculty', models.CharField(max_length=75, verbose_name='Bölüm')),
                ('compeleted', models.BooleanField(verbose_name='Durum')),
            ],
        ),
    ]
