# Generated by Django 3.1.3 on 2020-11-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitionName', models.CharField(max_length=100, verbose_name='Yarışma Adı')),
                ('competitionComment', models.CharField(max_length=500, verbose_name='Yarışma Açıklaması')),
            ],
        ),
    ]
